//fizzbuzz_loop.cpp
//Author: Diba Mirza
//Created: 01-17
//Program to implement fizzbuzz, inputs generated by a for loop
//

#include <iostream>

using namespace std;

void fizzbuzz(int n){
    if(n%3==0 && n%5 == 0)
        cout<<"Fizzbuzz\n";
    else if(n%3 == 0 )
        cout<<"Fizz"<<endl;
    else if(n%5 ==0)
        cout<<"Buzz"<<endl;
    else
        cout<<n<<endl;
}


int main(){
    for(int x= 1; x< 16;x++){
        fizzbuzz(x);
    }
    return 0;
}

